// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type SkillDraftResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *SkillDraftResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SkillDraftResponseClassView) PropertyResponse_type() (ClassPropertyView, error) {
	return t.inner.Property("response_type")
}

func (t *SkillDraftResponseClassView) PropertyMessage() (ClassPropertyView, error) {
	return t.inner.Property("message")
}

func (t *SkillDraftResponseClassView) PropertySkill_content() (ClassPropertyView, error) {
	return t.inner.Property("skill_content")
}

func (t *TypeBuilder) SkillDraftResponse() (*SkillDraftResponseClassView, error) {
	bld, err := t.inner.Class("SkillDraftResponse")
	if err != nil {
		return nil, err
	}
	return &SkillDraftResponseClassView{inner: bld}, nil
}

func (t *SkillDraftResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
