// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: filesystem.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FilesystemService_GetDirectoryAccess_FullMethodName   = "/filesystem.FilesystemService/GetDirectoryAccess"
	FilesystemService_SaveDirectoryAccess_FullMethodName  = "/filesystem.FilesystemService/SaveDirectoryAccess"
	FilesystemService_GetDirectoryContent_FullMethodName  = "/filesystem.FilesystemService/GetDirectoryContent"
	FilesystemService_SaveDirectoryContent_FullMethodName = "/filesystem.FilesystemService/SaveDirectoryContent"
	FilesystemService_GetFileMetadata_FullMethodName      = "/filesystem.FilesystemService/GetFileMetadata"
	FilesystemService_SaveFileMetadata_FullMethodName     = "/filesystem.FilesystemService/SaveFileMetadata"
	FilesystemService_ListDirectory_FullMethodName        = "/filesystem.FilesystemService/ListDirectory"
	FilesystemService_RenameDirectory_FullMethodName      = "/filesystem.FilesystemService/RenameDirectory"
	FilesystemService_DeleteDirectory_FullMethodName      = "/filesystem.FilesystemService/DeleteDirectory"
)

// FilesystemServiceClient is the client API for FilesystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesystemServiceClient interface {
	// Directory Access Metadata
	GetDirectoryAccess(ctx context.Context, in *GetDirectoryAccessRequest, opts ...grpc.CallOption) (*GetDirectoryAccessResponse, error)
	SaveDirectoryAccess(ctx context.Context, in *SaveDirectoryAccessRequest, opts ...grpc.CallOption) (*SaveDirectoryAccessResponse, error)
	// Directory Content Metadata
	GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (*GetDirectoryContentResponse, error)
	SaveDirectoryContent(ctx context.Context, in *SaveDirectoryContentRequest, opts ...grpc.CallOption) (*SaveDirectoryContentResponse, error)
	// File Metadata
	GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error)
	SaveFileMetadata(ctx context.Context, in *SaveFileMetadataRequest, opts ...grpc.CallOption) (*SaveFileMetadataResponse, error)
	// Directory Operations
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	RenameDirectory(ctx context.Context, in *RenameDirectoryRequest, opts ...grpc.CallOption) (*RenameDirectoryResponse, error)
	DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error)
}

type filesystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesystemServiceClient(cc grpc.ClientConnInterface) FilesystemServiceClient {
	return &filesystemServiceClient{cc}
}

func (c *filesystemServiceClient) GetDirectoryAccess(ctx context.Context, in *GetDirectoryAccessRequest, opts ...grpc.CallOption) (*GetDirectoryAccessResponse, error) {
	out := new(GetDirectoryAccessResponse)
	err := c.cc.Invoke(ctx, FilesystemService_GetDirectoryAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) SaveDirectoryAccess(ctx context.Context, in *SaveDirectoryAccessRequest, opts ...grpc.CallOption) (*SaveDirectoryAccessResponse, error) {
	out := new(SaveDirectoryAccessResponse)
	err := c.cc.Invoke(ctx, FilesystemService_SaveDirectoryAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (*GetDirectoryContentResponse, error) {
	out := new(GetDirectoryContentResponse)
	err := c.cc.Invoke(ctx, FilesystemService_GetDirectoryContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) SaveDirectoryContent(ctx context.Context, in *SaveDirectoryContentRequest, opts ...grpc.CallOption) (*SaveDirectoryContentResponse, error) {
	out := new(SaveDirectoryContentResponse)
	err := c.cc.Invoke(ctx, FilesystemService_SaveDirectoryContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error) {
	out := new(GetFileMetadataResponse)
	err := c.cc.Invoke(ctx, FilesystemService_GetFileMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) SaveFileMetadata(ctx context.Context, in *SaveFileMetadataRequest, opts ...grpc.CallOption) (*SaveFileMetadataResponse, error) {
	out := new(SaveFileMetadataResponse)
	err := c.cc.Invoke(ctx, FilesystemService_SaveFileMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	out := new(ListDirectoryResponse)
	err := c.cc.Invoke(ctx, FilesystemService_ListDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) RenameDirectory(ctx context.Context, in *RenameDirectoryRequest, opts ...grpc.CallOption) (*RenameDirectoryResponse, error) {
	out := new(RenameDirectoryResponse)
	err := c.cc.Invoke(ctx, FilesystemService_RenameDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemServiceClient) DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error) {
	out := new(DeleteDirectoryResponse)
	err := c.cc.Invoke(ctx, FilesystemService_DeleteDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesystemServiceServer is the server API for FilesystemService service.
// All implementations must embed UnimplementedFilesystemServiceServer
// for forward compatibility
type FilesystemServiceServer interface {
	// Directory Access Metadata
	GetDirectoryAccess(context.Context, *GetDirectoryAccessRequest) (*GetDirectoryAccessResponse, error)
	SaveDirectoryAccess(context.Context, *SaveDirectoryAccessRequest) (*SaveDirectoryAccessResponse, error)
	// Directory Content Metadata
	GetDirectoryContent(context.Context, *GetDirectoryContentRequest) (*GetDirectoryContentResponse, error)
	SaveDirectoryContent(context.Context, *SaveDirectoryContentRequest) (*SaveDirectoryContentResponse, error)
	// File Metadata
	GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error)
	SaveFileMetadata(context.Context, *SaveFileMetadataRequest) (*SaveFileMetadataResponse, error)
	// Directory Operations
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	RenameDirectory(context.Context, *RenameDirectoryRequest) (*RenameDirectoryResponse, error)
	DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error)
	mustEmbedUnimplementedFilesystemServiceServer()
}

// UnimplementedFilesystemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilesystemServiceServer struct {
}

func (UnimplementedFilesystemServiceServer) GetDirectoryAccess(context.Context, *GetDirectoryAccessRequest) (*GetDirectoryAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectoryAccess not implemented")
}
func (UnimplementedFilesystemServiceServer) SaveDirectoryAccess(context.Context, *SaveDirectoryAccessRequest) (*SaveDirectoryAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDirectoryAccess not implemented")
}
func (UnimplementedFilesystemServiceServer) GetDirectoryContent(context.Context, *GetDirectoryContentRequest) (*GetDirectoryContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectoryContent not implemented")
}
func (UnimplementedFilesystemServiceServer) SaveDirectoryContent(context.Context, *SaveDirectoryContentRequest) (*SaveDirectoryContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDirectoryContent not implemented")
}
func (UnimplementedFilesystemServiceServer) GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedFilesystemServiceServer) SaveFileMetadata(context.Context, *SaveFileMetadataRequest) (*SaveFileMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFileMetadata not implemented")
}
func (UnimplementedFilesystemServiceServer) ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedFilesystemServiceServer) RenameDirectory(context.Context, *RenameDirectoryRequest) (*RenameDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameDirectory not implemented")
}
func (UnimplementedFilesystemServiceServer) DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDirectory not implemented")
}
func (UnimplementedFilesystemServiceServer) mustEmbedUnimplementedFilesystemServiceServer() {}

// UnsafeFilesystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesystemServiceServer will
// result in compilation errors.
type UnsafeFilesystemServiceServer interface {
	mustEmbedUnimplementedFilesystemServiceServer()
}

func RegisterFilesystemServiceServer(s grpc.ServiceRegistrar, srv FilesystemServiceServer) {
	s.RegisterService(&FilesystemService_ServiceDesc, srv)
}

func _FilesystemService_GetDirectoryAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).GetDirectoryAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_GetDirectoryAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).GetDirectoryAccess(ctx, req.(*GetDirectoryAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_SaveDirectoryAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDirectoryAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).SaveDirectoryAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_SaveDirectoryAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).SaveDirectoryAccess(ctx, req.(*SaveDirectoryAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_GetDirectoryContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).GetDirectoryContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_GetDirectoryContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).GetDirectoryContent(ctx, req.(*GetDirectoryContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_SaveDirectoryContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDirectoryContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).SaveDirectoryContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_SaveDirectoryContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).SaveDirectoryContent(ctx, req.(*SaveDirectoryContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).GetFileMetadata(ctx, req.(*GetFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_SaveFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).SaveFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_SaveFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).SaveFileMetadata(ctx, req.(*SaveFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_RenameDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).RenameDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_RenameDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).RenameDirectory(ctx, req.(*RenameDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesystemService_DeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServiceServer).DeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesystemService_DeleteDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServiceServer).DeleteDirectory(ctx, req.(*DeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesystemService_ServiceDesc is the grpc.ServiceDesc for FilesystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filesystem.FilesystemService",
	HandlerType: (*FilesystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectoryAccess",
			Handler:    _FilesystemService_GetDirectoryAccess_Handler,
		},
		{
			MethodName: "SaveDirectoryAccess",
			Handler:    _FilesystemService_SaveDirectoryAccess_Handler,
		},
		{
			MethodName: "GetDirectoryContent",
			Handler:    _FilesystemService_GetDirectoryContent_Handler,
		},
		{
			MethodName: "SaveDirectoryContent",
			Handler:    _FilesystemService_SaveDirectoryContent_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _FilesystemService_GetFileMetadata_Handler,
		},
		{
			MethodName: "SaveFileMetadata",
			Handler:    _FilesystemService_SaveFileMetadata_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _FilesystemService_ListDirectory_Handler,
		},
		{
			MethodName: "RenameDirectory",
			Handler:    _FilesystemService_RenameDirectory_Handler,
		},
		{
			MethodName: "DeleteDirectory",
			Handler:    _FilesystemService_DeleteDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filesystem.proto",
}
