// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: sources.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SourceService_Stat_FullMethodName     = "/sources.SourceService/Stat"
	SourceService_ReadDir_FullMethodName  = "/sources.SourceService/ReadDir"
	SourceService_Read_FullMethodName     = "/sources.SourceService/Read"
	SourceService_Readlink_FullMethodName = "/sources.SourceService/Readlink"
)

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourceServiceClient interface {
	// Stat returns file/directory attributes for a source path
	Stat(ctx context.Context, in *SourceStatRequest, opts ...grpc.CallOption) (*SourceStatResponse, error)
	// ReadDir lists directory contents with enriched metadata
	ReadDir(ctx context.Context, in *SourceReadDirRequest, opts ...grpc.CallOption) (*SourceReadDirResponse, error)
	// Read reads file content from a source
	Read(ctx context.Context, in *SourceReadRequest, opts ...grpc.CallOption) (*SourceReadResponse, error)
	// Readlink reads a symbolic link target (for friendly aliases)
	Readlink(ctx context.Context, in *SourceReadlinkRequest, opts ...grpc.CallOption) (*SourceReadlinkResponse, error)
}

type sourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceServiceClient(cc grpc.ClientConnInterface) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) Stat(ctx context.Context, in *SourceStatRequest, opts ...grpc.CallOption) (*SourceStatResponse, error) {
	out := new(SourceStatResponse)
	err := c.cc.Invoke(ctx, SourceService_Stat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) ReadDir(ctx context.Context, in *SourceReadDirRequest, opts ...grpc.CallOption) (*SourceReadDirResponse, error) {
	out := new(SourceReadDirResponse)
	err := c.cc.Invoke(ctx, SourceService_ReadDir_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Read(ctx context.Context, in *SourceReadRequest, opts ...grpc.CallOption) (*SourceReadResponse, error) {
	out := new(SourceReadResponse)
	err := c.cc.Invoke(ctx, SourceService_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Readlink(ctx context.Context, in *SourceReadlinkRequest, opts ...grpc.CallOption) (*SourceReadlinkResponse, error) {
	out := new(SourceReadlinkResponse)
	err := c.cc.Invoke(ctx, SourceService_Readlink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
// All implementations must embed UnimplementedSourceServiceServer
// for forward compatibility
type SourceServiceServer interface {
	// Stat returns file/directory attributes for a source path
	Stat(context.Context, *SourceStatRequest) (*SourceStatResponse, error)
	// ReadDir lists directory contents with enriched metadata
	ReadDir(context.Context, *SourceReadDirRequest) (*SourceReadDirResponse, error)
	// Read reads file content from a source
	Read(context.Context, *SourceReadRequest) (*SourceReadResponse, error)
	// Readlink reads a symbolic link target (for friendly aliases)
	Readlink(context.Context, *SourceReadlinkRequest) (*SourceReadlinkResponse, error)
	mustEmbedUnimplementedSourceServiceServer()
}

// UnimplementedSourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSourceServiceServer struct {
}

func (UnimplementedSourceServiceServer) Stat(context.Context, *SourceStatRequest) (*SourceStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSourceServiceServer) ReadDir(context.Context, *SourceReadDirRequest) (*SourceReadDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDir not implemented")
}
func (UnimplementedSourceServiceServer) Read(context.Context, *SourceReadRequest) (*SourceReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedSourceServiceServer) Readlink(context.Context, *SourceReadlinkRequest) (*SourceReadlinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Readlink not implemented")
}
func (UnimplementedSourceServiceServer) mustEmbedUnimplementedSourceServiceServer() {}

// UnsafeSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServiceServer will
// result in compilation errors.
type UnsafeSourceServiceServer interface {
	mustEmbedUnimplementedSourceServiceServer()
}

func RegisterSourceServiceServer(s grpc.ServiceRegistrar, srv SourceServiceServer) {
	s.RegisterService(&SourceService_ServiceDesc, srv)
}

func _SourceService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Stat(ctx, req.(*SourceStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_ReadDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).ReadDir(ctx, req.(*SourceReadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Read(ctx, req.(*SourceReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Readlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Readlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Readlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Readlink(ctx, req.(*SourceReadlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceService_ServiceDesc is the grpc.ServiceDesc for SourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sources.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _SourceService_Stat_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _SourceService_ReadDir_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SourceService_Read_Handler,
		},
		{
			MethodName: "Readlink",
			Handler:    _SourceService_Readlink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sources.proto",
}
