// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: sources.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SourceService_Stat_FullMethodName        = "/sources.SourceService/Stat"
	SourceService_ReadDir_FullMethodName     = "/sources.SourceService/ReadDir"
	SourceService_Read_FullMethodName        = "/sources.SourceService/Read"
	SourceService_Readlink_FullMethodName    = "/sources.SourceService/Readlink"
	SourceService_CreateView_FullMethodName  = "/sources.SourceService/CreateView"
	SourceService_GetView_FullMethodName     = "/sources.SourceService/GetView"
	SourceService_ListViews_FullMethodName   = "/sources.SourceService/ListViews"
	SourceService_DeleteView_FullMethodName  = "/sources.SourceService/DeleteView"
	SourceService_UpdateView_FullMethodName  = "/sources.SourceService/UpdateView"
	SourceService_ExecuteView_FullMethodName = "/sources.SourceService/ExecuteView"
	SourceService_SyncView_FullMethodName    = "/sources.SourceService/SyncView"
)

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourceServiceClient interface {
	// Stat returns file/directory attributes for a source path
	Stat(ctx context.Context, in *SourceStatRequest, opts ...grpc.CallOption) (*SourceStatResponse, error)
	// ReadDir lists directory contents with enriched metadata
	ReadDir(ctx context.Context, in *SourceReadDirRequest, opts ...grpc.CallOption) (*SourceReadDirResponse, error)
	// Read reads file content from a source
	Read(ctx context.Context, in *SourceReadRequest, opts ...grpc.CallOption) (*SourceReadResponse, error)
	// Readlink reads a symbolic link target (for friendly aliases)
	Readlink(ctx context.Context, in *SourceReadlinkRequest, opts ...grpc.CallOption) (*SourceReadlinkResponse, error)
	// CreateView creates a new source view (called on mkdir/touch)
	CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error)
	// GetView retrieves a view by its path
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error)
	// ListViews lists views under a parent path
	ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error)
	// DeleteView removes a view by external_id
	DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*DeleteViewResponse, error)
	// UpdateView updates an existing view's name/guidance
	UpdateView(ctx context.Context, in *UpdateViewRequest, opts ...grpc.CallOption) (*UpdateViewResponse, error)
	// ExecuteView runs a view's query and returns materialized results
	ExecuteView(ctx context.Context, in *ExecuteViewRequest, opts ...grpc.CallOption) (*ExecuteViewResponse, error)
	// SyncView re-executes a view's query, refreshing cached metadata
	SyncView(ctx context.Context, in *SyncViewRequest, opts ...grpc.CallOption) (*SyncViewResponse, error)
}

type sourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceServiceClient(cc grpc.ClientConnInterface) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) Stat(ctx context.Context, in *SourceStatRequest, opts ...grpc.CallOption) (*SourceStatResponse, error) {
	out := new(SourceStatResponse)
	err := c.cc.Invoke(ctx, SourceService_Stat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) ReadDir(ctx context.Context, in *SourceReadDirRequest, opts ...grpc.CallOption) (*SourceReadDirResponse, error) {
	out := new(SourceReadDirResponse)
	err := c.cc.Invoke(ctx, SourceService_ReadDir_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Read(ctx context.Context, in *SourceReadRequest, opts ...grpc.CallOption) (*SourceReadResponse, error) {
	out := new(SourceReadResponse)
	err := c.cc.Invoke(ctx, SourceService_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Readlink(ctx context.Context, in *SourceReadlinkRequest, opts ...grpc.CallOption) (*SourceReadlinkResponse, error) {
	out := new(SourceReadlinkResponse)
	err := c.cc.Invoke(ctx, SourceService_Readlink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error) {
	out := new(CreateViewResponse)
	err := c.cc.Invoke(ctx, SourceService_CreateView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error) {
	out := new(GetViewResponse)
	err := c.cc.Invoke(ctx, SourceService_GetView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error) {
	out := new(ListViewsResponse)
	err := c.cc.Invoke(ctx, SourceService_ListViews_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*DeleteViewResponse, error) {
	out := new(DeleteViewResponse)
	err := c.cc.Invoke(ctx, SourceService_DeleteView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) UpdateView(ctx context.Context, in *UpdateViewRequest, opts ...grpc.CallOption) (*UpdateViewResponse, error) {
	out := new(UpdateViewResponse)
	err := c.cc.Invoke(ctx, SourceService_UpdateView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) ExecuteView(ctx context.Context, in *ExecuteViewRequest, opts ...grpc.CallOption) (*ExecuteViewResponse, error) {
	out := new(ExecuteViewResponse)
	err := c.cc.Invoke(ctx, SourceService_ExecuteView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) SyncView(ctx context.Context, in *SyncViewRequest, opts ...grpc.CallOption) (*SyncViewResponse, error) {
	out := new(SyncViewResponse)
	err := c.cc.Invoke(ctx, SourceService_SyncView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
// All implementations must embed UnimplementedSourceServiceServer
// for forward compatibility
type SourceServiceServer interface {
	// Stat returns file/directory attributes for a source path
	Stat(context.Context, *SourceStatRequest) (*SourceStatResponse, error)
	// ReadDir lists directory contents with enriched metadata
	ReadDir(context.Context, *SourceReadDirRequest) (*SourceReadDirResponse, error)
	// Read reads file content from a source
	Read(context.Context, *SourceReadRequest) (*SourceReadResponse, error)
	// Readlink reads a symbolic link target (for friendly aliases)
	Readlink(context.Context, *SourceReadlinkRequest) (*SourceReadlinkResponse, error)
	// CreateView creates a new source view (called on mkdir/touch)
	CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error)
	// GetView retrieves a view by its path
	GetView(context.Context, *GetViewRequest) (*GetViewResponse, error)
	// ListViews lists views under a parent path
	ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error)
	// DeleteView removes a view by external_id
	DeleteView(context.Context, *DeleteViewRequest) (*DeleteViewResponse, error)
	// UpdateView updates an existing view's name/guidance
	UpdateView(context.Context, *UpdateViewRequest) (*UpdateViewResponse, error)
	// ExecuteView runs a view's query and returns materialized results
	ExecuteView(context.Context, *ExecuteViewRequest) (*ExecuteViewResponse, error)
	// SyncView re-executes a view's query, refreshing cached metadata
	SyncView(context.Context, *SyncViewRequest) (*SyncViewResponse, error)
	mustEmbedUnimplementedSourceServiceServer()
}

// UnimplementedSourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSourceServiceServer struct {
}

func (UnimplementedSourceServiceServer) Stat(context.Context, *SourceStatRequest) (*SourceStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSourceServiceServer) ReadDir(context.Context, *SourceReadDirRequest) (*SourceReadDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDir not implemented")
}
func (UnimplementedSourceServiceServer) Read(context.Context, *SourceReadRequest) (*SourceReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedSourceServiceServer) Readlink(context.Context, *SourceReadlinkRequest) (*SourceReadlinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Readlink not implemented")
}
func (UnimplementedSourceServiceServer) CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateView not implemented")
}
func (UnimplementedSourceServiceServer) GetView(context.Context, *GetViewRequest) (*GetViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedSourceServiceServer) ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListViews not implemented")
}
func (UnimplementedSourceServiceServer) DeleteView(context.Context, *DeleteViewRequest) (*DeleteViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteView not implemented")
}
func (UnimplementedSourceServiceServer) UpdateView(context.Context, *UpdateViewRequest) (*UpdateViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateView not implemented")
}
func (UnimplementedSourceServiceServer) ExecuteView(context.Context, *ExecuteViewRequest) (*ExecuteViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteView not implemented")
}
func (UnimplementedSourceServiceServer) SyncView(context.Context, *SyncViewRequest) (*SyncViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncView not implemented")
}
func (UnimplementedSourceServiceServer) mustEmbedUnimplementedSourceServiceServer() {}

// UnsafeSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServiceServer will
// result in compilation errors.
type UnsafeSourceServiceServer interface {
	mustEmbedUnimplementedSourceServiceServer()
}

func RegisterSourceServiceServer(s grpc.ServiceRegistrar, srv SourceServiceServer) {
	s.RegisterService(&SourceService_ServiceDesc, srv)
}

func _SourceService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Stat(ctx, req.(*SourceStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_ReadDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).ReadDir(ctx, req.(*SourceReadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Read(ctx, req.(*SourceReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Readlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceReadlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Readlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Readlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Readlink(ctx, req.(*SourceReadlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_CreateView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).CreateView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_CreateView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).CreateView(ctx, req.(*CreateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_GetView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_ListViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).ListViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_ListViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).ListViews(ctx, req.(*ListViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_DeleteView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).DeleteView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_DeleteView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).DeleteView(ctx, req.(*DeleteViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_UpdateView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).UpdateView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_UpdateView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).UpdateView(ctx, req.(*UpdateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_ExecuteView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).ExecuteView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_ExecuteView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).ExecuteView(ctx, req.(*ExecuteViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_SyncView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).SyncView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_SyncView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).SyncView(ctx, req.(*SyncViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceService_ServiceDesc is the grpc.ServiceDesc for SourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sources.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _SourceService_Stat_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _SourceService_ReadDir_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SourceService_Read_Handler,
		},
		{
			MethodName: "Readlink",
			Handler:    _SourceService_Readlink_Handler,
		},
		{
			MethodName: "CreateView",
			Handler:    _SourceService_CreateView_Handler,
		},
		{
			MethodName: "GetView",
			Handler:    _SourceService_GetView_Handler,
		},
		{
			MethodName: "ListViews",
			Handler:    _SourceService_ListViews_Handler,
		},
		{
			MethodName: "DeleteView",
			Handler:    _SourceService_DeleteView_Handler,
		},
		{
			MethodName: "UpdateView",
			Handler:    _SourceService_UpdateView_Handler,
		},
		{
			MethodName: "ExecuteView",
			Handler:    _SourceService_ExecuteView_Handler,
		},
		{
			MethodName: "SyncView",
			Handler:    _SourceService_SyncView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sources.proto",
}
