// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: sources.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceFileInfo contains file/directory metadata
type SourceFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size   int64  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Mode   uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Mtime  int64  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"` // Unix timestamp
	IsDir  bool   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	IsLink bool   `protobuf:"varint,5,opt,name=is_link,json=isLink,proto3" json:"is_link,omitempty"`
}

func (x *SourceFileInfo) Reset() {
	*x = SourceFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceFileInfo) ProtoMessage() {}

func (x *SourceFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceFileInfo.ProtoReflect.Descriptor instead.
func (*SourceFileInfo) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{0}
}

func (x *SourceFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SourceFileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SourceFileInfo) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *SourceFileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *SourceFileInfo) GetIsLink() bool {
	if x != nil {
		return x.IsLink
	}
	return false
}

// SourceDirEntry represents a directory entry with full metadata
type SourceDirEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode     uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir    bool   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size     int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mtime    int64  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`                      // Unix timestamp
	ResultId string `protobuf:"bytes,6,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"` // Provider-specific ID for content retrieval (optional)
}

func (x *SourceDirEntry) Reset() {
	*x = SourceDirEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceDirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceDirEntry) ProtoMessage() {}

func (x *SourceDirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceDirEntry.ProtoReflect.Descriptor instead.
func (*SourceDirEntry) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{1}
}

func (x *SourceDirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceDirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SourceDirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *SourceDirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SourceDirEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *SourceDirEntry) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

// Stat
type SourceStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Path relative to /sources (e.g., "github/views/repos.json")
}

func (x *SourceStatRequest) Reset() {
	*x = SourceStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatRequest) ProtoMessage() {}

func (x *SourceStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatRequest.ProtoReflect.Descriptor instead.
func (*SourceStatRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{2}
}

func (x *SourceStatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SourceStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool            `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Info  *SourceFileInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SourceStatResponse) Reset() {
	*x = SourceStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatResponse) ProtoMessage() {}

func (x *SourceStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatResponse.ProtoReflect.Descriptor instead.
func (*SourceStatResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{3}
}

func (x *SourceStatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SourceStatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SourceStatResponse) GetInfo() *SourceFileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ReadDir
type SourceReadDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SourceReadDirRequest) Reset() {
	*x = SourceReadDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadDirRequest) ProtoMessage() {}

func (x *SourceReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadDirRequest.ProtoReflect.Descriptor instead.
func (*SourceReadDirRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{4}
}

func (x *SourceReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SourceReadDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool              `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error   string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Entries []*SourceDirEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *SourceReadDirResponse) Reset() {
	*x = SourceReadDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadDirResponse) ProtoMessage() {}

func (x *SourceReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadDirResponse.ProtoReflect.Descriptor instead.
func (*SourceReadDirResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{5}
}

func (x *SourceReadDirResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SourceReadDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SourceReadDirResponse) GetEntries() []*SourceDirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Read
type SourceReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length int64  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 0 means read to end
}

func (x *SourceReadRequest) Reset() {
	*x = SourceReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadRequest) ProtoMessage() {}

func (x *SourceReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadRequest.ProtoReflect.Descriptor instead.
func (*SourceReadRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{6}
}

func (x *SourceReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SourceReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SourceReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type SourceReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SourceReadResponse) Reset() {
	*x = SourceReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadResponse) ProtoMessage() {}

func (x *SourceReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadResponse.ProtoReflect.Descriptor instead.
func (*SourceReadResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{7}
}

func (x *SourceReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SourceReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SourceReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Readlink
type SourceReadlinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SourceReadlinkRequest) Reset() {
	*x = SourceReadlinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadlinkRequest) ProtoMessage() {}

func (x *SourceReadlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadlinkRequest.ProtoReflect.Descriptor instead.
func (*SourceReadlinkRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{8}
}

func (x *SourceReadlinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SourceReadlinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SourceReadlinkResponse) Reset() {
	*x = SourceReadlinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReadlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReadlinkResponse) ProtoMessage() {}

func (x *SourceReadlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReadlinkResponse.ProtoReflect.Descriptor instead.
func (*SourceReadlinkResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{9}
}

func (x *SourceReadlinkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SourceReadlinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SourceReadlinkResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// SmartQuery represents a stored query that materializes as filesystem content
type SmartQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId   string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Integration  string `protobuf:"bytes,2,opt,name=integration,proto3" json:"integration,omitempty"`                       // "gmail", "gdrive", etc.
	Path         string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                     // Full path: "/sources/gmail/unread-emails"
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                     // Folder/file name
	QuerySpec    string `protobuf:"bytes,5,opt,name=query_spec,json=querySpec,proto3" json:"query_spec,omitempty"`          // JSON query params from LLM
	Guidance     string `protobuf:"bytes,6,opt,name=guidance,proto3" json:"guidance,omitempty"`                             // User-provided context for inference
	OutputFormat string `protobuf:"bytes,7,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // "folder" or "file"
	FileExt      string `protobuf:"bytes,8,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`                // For files: ".json", ".md"
	CacheTtl     int32  `protobuf:"varint,9,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`            // Seconds, 0 = always live
	CreatedAt    int64  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // Unix timestamp
	UpdatedAt    int64  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *SmartQuery) Reset() {
	*x = SmartQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartQuery) ProtoMessage() {}

func (x *SmartQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartQuery.ProtoReflect.Descriptor instead.
func (*SmartQuery) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{10}
}

func (x *SmartQuery) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SmartQuery) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *SmartQuery) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SmartQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmartQuery) GetQuerySpec() string {
	if x != nil {
		return x.QuerySpec
	}
	return ""
}

func (x *SmartQuery) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

func (x *SmartQuery) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *SmartQuery) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *SmartQuery) GetCacheTtl() int32 {
	if x != nil {
		return x.CacheTtl
	}
	return 0
}

func (x *SmartQuery) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SmartQuery) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateSmartQuery - creates a query from a folder/file name via LLM inference
type CreateSmartQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration  string `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`                       // e.g., "gmail"
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // Folder name like "unread-emails"
	Guidance     string `protobuf:"bytes,3,opt,name=guidance,proto3" json:"guidance,omitempty"`                             // Optional extra context for LLM
	OutputFormat string `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // "folder" or "file"
	FileExt      string `protobuf:"bytes,5,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`                // For files: ".json", ".md"
}

func (x *CreateSmartQueryRequest) Reset() {
	*x = CreateSmartQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSmartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmartQueryRequest) ProtoMessage() {}

func (x *CreateSmartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmartQueryRequest.ProtoReflect.Descriptor instead.
func (*CreateSmartQueryRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSmartQueryRequest) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *CreateSmartQueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSmartQueryRequest) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

func (x *CreateSmartQueryRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *CreateSmartQueryRequest) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

type CreateSmartQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Query *SmartQuery `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *CreateSmartQueryResponse) Reset() {
	*x = CreateSmartQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSmartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmartQueryResponse) ProtoMessage() {}

func (x *CreateSmartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmartQueryResponse.ProtoReflect.Descriptor instead.
func (*CreateSmartQueryResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSmartQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateSmartQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateSmartQueryResponse) GetQuery() *SmartQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// GetSmartQuery - retrieves a query by path
type GetSmartQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Full path: "/sources/gmail/unread-emails"
}

func (x *GetSmartQueryRequest) Reset() {
	*x = GetSmartQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSmartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmartQueryRequest) ProtoMessage() {}

func (x *GetSmartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmartQueryRequest.ProtoReflect.Descriptor instead.
func (*GetSmartQueryRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{13}
}

func (x *GetSmartQueryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetSmartQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Query *SmartQuery `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // nil if not found
}

func (x *GetSmartQueryResponse) Reset() {
	*x = GetSmartQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSmartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmartQueryResponse) ProtoMessage() {}

func (x *GetSmartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmartQueryResponse.ProtoReflect.Descriptor instead.
func (*GetSmartQueryResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{14}
}

func (x *GetSmartQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetSmartQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetSmartQueryResponse) GetQuery() *SmartQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// ListSmartQueries - lists queries under a parent path
type ListSmartQueriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentPath string `protobuf:"bytes,1,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"` // e.g., "/sources/gmail"
}

func (x *ListSmartQueriesRequest) Reset() {
	*x = ListSmartQueriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSmartQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSmartQueriesRequest) ProtoMessage() {}

func (x *ListSmartQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSmartQueriesRequest.ProtoReflect.Descriptor instead.
func (*ListSmartQueriesRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{15}
}

func (x *ListSmartQueriesRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

type ListSmartQueriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error   string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Queries []*SmartQuery `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *ListSmartQueriesResponse) Reset() {
	*x = ListSmartQueriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSmartQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSmartQueriesResponse) ProtoMessage() {}

func (x *ListSmartQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSmartQueriesResponse.ProtoReflect.Descriptor instead.
func (*ListSmartQueriesResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{16}
}

func (x *ListSmartQueriesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListSmartQueriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListSmartQueriesResponse) GetQueries() []*SmartQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

// DeleteSmartQuery - removes a query by external_id
type DeleteSmartQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Stable query ID (from SmartQuery.external_id)
}

func (x *DeleteSmartQueryRequest) Reset() {
	*x = DeleteSmartQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSmartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSmartQueryRequest) ProtoMessage() {}

func (x *DeleteSmartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSmartQueryRequest.ProtoReflect.Descriptor instead.
func (*DeleteSmartQueryRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteSmartQueryRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type DeleteSmartQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteSmartQueryResponse) Reset() {
	*x = DeleteSmartQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSmartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSmartQueryResponse) ProtoMessage() {}

func (x *DeleteSmartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSmartQueryResponse.ProtoReflect.Descriptor instead.
func (*DeleteSmartQueryResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteSmartQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteSmartQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateSmartQuery - updates an existing query's name and/or guidance
type UpdateSmartQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Stable query ID (from SmartQuery.external_id)
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // New name (optional, triggers rename + path update)
	Guidance   string `protobuf:"bytes,3,opt,name=guidance,proto3" json:"guidance,omitempty"`                       // New guidance (triggers re-inference of query_spec)
}

func (x *UpdateSmartQueryRequest) Reset() {
	*x = UpdateSmartQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSmartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSmartQueryRequest) ProtoMessage() {}

func (x *UpdateSmartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSmartQueryRequest.ProtoReflect.Descriptor instead.
func (*UpdateSmartQueryRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateSmartQueryRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UpdateSmartQueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSmartQueryRequest) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

type UpdateSmartQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Query *SmartQuery `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *UpdateSmartQueryResponse) Reset() {
	*x = UpdateSmartQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSmartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSmartQueryResponse) ProtoMessage() {}

func (x *UpdateSmartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSmartQueryResponse.ProtoReflect.Descriptor instead.
func (*UpdateSmartQueryResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateSmartQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateSmartQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateSmartQueryResponse) GetQuery() *SmartQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// ExecuteSmartQuery - runs a query and returns results
type ExecuteSmartQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                         // Query path: "/sources/gmail/unread-emails"
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                 // Optional: specific file to read from folder results
	ResultId string `protobuf:"bytes,3,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"` // Optional: provider-specific ID for direct content retrieval
}

func (x *ExecuteSmartQueryRequest) Reset() {
	*x = ExecuteSmartQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteSmartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSmartQueryRequest) ProtoMessage() {}

func (x *ExecuteSmartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSmartQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSmartQueryRequest) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteSmartQueryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecuteSmartQueryRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExecuteSmartQueryRequest) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

type ExecuteSmartQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool              `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error    string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Entries  []*SourceDirEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`                   // For folder mode: directory entries
	FileData []byte            `protobuf:"bytes,4,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // For file mode or specific filename: content
}

func (x *ExecuteSmartQueryResponse) Reset() {
	*x = ExecuteSmartQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sources_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteSmartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSmartQueryResponse) ProtoMessage() {}

func (x *ExecuteSmartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sources_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSmartQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSmartQueryResponse) Descriptor() ([]byte, []int) {
	return file_sources_proto_rawDescGZIP(), []int{22}
}

func (x *ExecuteSmartQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecuteSmartQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteSmartQueryResponse) GetEntries() []*SourceDirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ExecuteSmartQueryResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

var File_sources_proto protoreflect.FileDescriptor

var file_sources_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x7e, 0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64,
	0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x96, 0x01, 0x0a, 0x0e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x69, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49,
	0x64, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x67, 0x0a, 0x12, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x70, 0x0a, 0x15, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x44, 0x69, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x57, 0x0a, 0x11, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x4e, 0x0a, 0x12, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x15, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x56, 0x0a, 0x16, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22,
	0xcd, 0x02, 0x0a, 0x0a, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x64,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x75, 0x69, 0x64,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x45, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x74, 0x74,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x54, 0x74,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0xab, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x22, 0x6b, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x29, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x3a, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x6f, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d,
	0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x3a, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x18, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6a, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x6b, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x67, 0x0a, 0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x22, 0x91, 0x01,
	0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x69, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x32, 0xb8, 0x06, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x12,
	0x1d, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f,
	0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x2e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x20, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6d, 0x61, 0x72,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x20, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6d,
	0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5a, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x61, 0x6d, 0x2d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x69, 0x72, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sources_proto_rawDescOnce sync.Once
	file_sources_proto_rawDescData = file_sources_proto_rawDesc
)

func file_sources_proto_rawDescGZIP() []byte {
	file_sources_proto_rawDescOnce.Do(func() {
		file_sources_proto_rawDescData = protoimpl.X.CompressGZIP(file_sources_proto_rawDescData)
	})
	return file_sources_proto_rawDescData
}

var file_sources_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_sources_proto_goTypes = []interface{}{
	(*SourceFileInfo)(nil),            // 0: sources.SourceFileInfo
	(*SourceDirEntry)(nil),            // 1: sources.SourceDirEntry
	(*SourceStatRequest)(nil),         // 2: sources.SourceStatRequest
	(*SourceStatResponse)(nil),        // 3: sources.SourceStatResponse
	(*SourceReadDirRequest)(nil),      // 4: sources.SourceReadDirRequest
	(*SourceReadDirResponse)(nil),     // 5: sources.SourceReadDirResponse
	(*SourceReadRequest)(nil),         // 6: sources.SourceReadRequest
	(*SourceReadResponse)(nil),        // 7: sources.SourceReadResponse
	(*SourceReadlinkRequest)(nil),     // 8: sources.SourceReadlinkRequest
	(*SourceReadlinkResponse)(nil),    // 9: sources.SourceReadlinkResponse
	(*SmartQuery)(nil),                // 10: sources.SmartQuery
	(*CreateSmartQueryRequest)(nil),   // 11: sources.CreateSmartQueryRequest
	(*CreateSmartQueryResponse)(nil),  // 12: sources.CreateSmartQueryResponse
	(*GetSmartQueryRequest)(nil),      // 13: sources.GetSmartQueryRequest
	(*GetSmartQueryResponse)(nil),     // 14: sources.GetSmartQueryResponse
	(*ListSmartQueriesRequest)(nil),   // 15: sources.ListSmartQueriesRequest
	(*ListSmartQueriesResponse)(nil),  // 16: sources.ListSmartQueriesResponse
	(*DeleteSmartQueryRequest)(nil),   // 17: sources.DeleteSmartQueryRequest
	(*DeleteSmartQueryResponse)(nil),  // 18: sources.DeleteSmartQueryResponse
	(*UpdateSmartQueryRequest)(nil),   // 19: sources.UpdateSmartQueryRequest
	(*UpdateSmartQueryResponse)(nil),  // 20: sources.UpdateSmartQueryResponse
	(*ExecuteSmartQueryRequest)(nil),  // 21: sources.ExecuteSmartQueryRequest
	(*ExecuteSmartQueryResponse)(nil), // 22: sources.ExecuteSmartQueryResponse
}
var file_sources_proto_depIdxs = []int32{
	0,  // 0: sources.SourceStatResponse.info:type_name -> sources.SourceFileInfo
	1,  // 1: sources.SourceReadDirResponse.entries:type_name -> sources.SourceDirEntry
	10, // 2: sources.CreateSmartQueryResponse.query:type_name -> sources.SmartQuery
	10, // 3: sources.GetSmartQueryResponse.query:type_name -> sources.SmartQuery
	10, // 4: sources.ListSmartQueriesResponse.queries:type_name -> sources.SmartQuery
	10, // 5: sources.UpdateSmartQueryResponse.query:type_name -> sources.SmartQuery
	1,  // 6: sources.ExecuteSmartQueryResponse.entries:type_name -> sources.SourceDirEntry
	2,  // 7: sources.SourceService.Stat:input_type -> sources.SourceStatRequest
	4,  // 8: sources.SourceService.ReadDir:input_type -> sources.SourceReadDirRequest
	6,  // 9: sources.SourceService.Read:input_type -> sources.SourceReadRequest
	8,  // 10: sources.SourceService.Readlink:input_type -> sources.SourceReadlinkRequest
	11, // 11: sources.SourceService.CreateSmartQuery:input_type -> sources.CreateSmartQueryRequest
	13, // 12: sources.SourceService.GetSmartQuery:input_type -> sources.GetSmartQueryRequest
	15, // 13: sources.SourceService.ListSmartQueries:input_type -> sources.ListSmartQueriesRequest
	17, // 14: sources.SourceService.DeleteSmartQuery:input_type -> sources.DeleteSmartQueryRequest
	19, // 15: sources.SourceService.UpdateSmartQuery:input_type -> sources.UpdateSmartQueryRequest
	21, // 16: sources.SourceService.ExecuteSmartQuery:input_type -> sources.ExecuteSmartQueryRequest
	3,  // 17: sources.SourceService.Stat:output_type -> sources.SourceStatResponse
	5,  // 18: sources.SourceService.ReadDir:output_type -> sources.SourceReadDirResponse
	7,  // 19: sources.SourceService.Read:output_type -> sources.SourceReadResponse
	9,  // 20: sources.SourceService.Readlink:output_type -> sources.SourceReadlinkResponse
	12, // 21: sources.SourceService.CreateSmartQuery:output_type -> sources.CreateSmartQueryResponse
	14, // 22: sources.SourceService.GetSmartQuery:output_type -> sources.GetSmartQueryResponse
	16, // 23: sources.SourceService.ListSmartQueries:output_type -> sources.ListSmartQueriesResponse
	18, // 24: sources.SourceService.DeleteSmartQuery:output_type -> sources.DeleteSmartQueryResponse
	20, // 25: sources.SourceService.UpdateSmartQuery:output_type -> sources.UpdateSmartQueryResponse
	22, // 26: sources.SourceService.ExecuteSmartQuery:output_type -> sources.ExecuteSmartQueryResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sources_proto_init() }
func file_sources_proto_init() {
	if File_sources_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sources_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceDirEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadlinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReadlinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSmartQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSmartQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSmartQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSmartQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSmartQueriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSmartQueriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSmartQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSmartQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSmartQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSmartQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteSmartQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sources_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteSmartQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sources_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sources_proto_goTypes,
		DependencyIndexes: file_sources_proto_depIdxs,
		MessageInfos:      file_sources_proto_msgTypes,
	}.Build()
	File_sources_proto = out.File
	file_sources_proto_rawDesc = nil
	file_sources_proto_goTypes = nil
	file_sources_proto_depIdxs = nil
}
