// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ApprovalSummaryClassView struct {
	inner baml.ClassBuilder
}

func (t *ApprovalSummaryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ApprovalSummaryClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *ApprovalSummaryClassView) PropertyDetails() (ClassPropertyView, error) {
	return t.inner.Property("details")
}

func (t *TypeBuilder) ApprovalSummary() (*ApprovalSummaryClassView, error) {
	bld, err := t.inner.Class("ApprovalSummary")
	if err != nil {
		return nil, err
	}
	return &ApprovalSummaryClassView{inner: bld}, nil
}

func (t *ApprovalSummaryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DataFieldClassView struct {
	inner baml.ClassBuilder
}

func (t *DataFieldClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DataFieldClassView) PropertyKey() (ClassPropertyView, error) {
	return t.inner.Property("key")
}

func (t *DataFieldClassView) PropertyValue() (ClassPropertyView, error) {
	return t.inner.Property("value")
}

func (t *DataFieldClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *DataFieldClassView) PropertyLabel() (ClassPropertyView, error) {
	return t.inner.Property("label")
}

func (t *TypeBuilder) DataField() (*DataFieldClassView, error) {
	bld, err := t.inner.Class("DataField")
	if err != nil {
		return nil, err
	}
	return &DataFieldClassView{inner: bld}, nil
}

func (t *DataFieldClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ExtractedOutputClassView struct {
	inner baml.ClassBuilder
}

func (t *ExtractedOutputClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ExtractedOutputClassView) PropertyKind() (ClassPropertyView, error) {
	return t.inner.Property("kind")
}

func (t *ExtractedOutputClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *ExtractedOutputClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *ExtractedOutputClassView) PropertyUri() (ClassPropertyView, error) {
	return t.inner.Property("uri")
}

func (t *ExtractedOutputClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *ExtractedOutputClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *ExtractedOutputClassView) PropertyArtifact_key() (ClassPropertyView, error) {
	return t.inner.Property("artifact_key")
}

func (t *ExtractedOutputClassView) PropertyArtifact_label() (ClassPropertyView, error) {
	return t.inner.Property("artifact_label")
}

func (t *ExtractedOutputClassView) PropertyArtifact_kind() (ClassPropertyView, error) {
	return t.inner.Property("artifact_kind")
}

func (t *ExtractedOutputClassView) PropertyTags() (ClassPropertyView, error) {
	return t.inner.Property("tags")
}

func (t *ExtractedOutputClassView) PropertyData_fields() (ClassPropertyView, error) {
	return t.inner.Property("data_fields")
}

func (t *TypeBuilder) ExtractedOutput() (*ExtractedOutputClassView, error) {
	bld, err := t.inner.Class("ExtractedOutput")
	if err != nil {
		return nil, err
	}
	return &ExtractedOutputClassView{inner: bld}, nil
}

func (t *ExtractedOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FollowUpSignalClassView struct {
	inner baml.ClassBuilder
}

func (t *FollowUpSignalClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FollowUpSignalClassView) PropertyIntent() (ClassPropertyView, error) {
	return t.inner.Property("intent")
}

func (t *FollowUpSignalClassView) PropertyDelay_minutes() (ClassPropertyView, error) {
	return t.inner.Property("delay_minutes")
}

func (t *FollowUpSignalClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *FollowUpSignalClassView) PropertyFollow_up_prompt() (ClassPropertyView, error) {
	return t.inner.Property("follow_up_prompt")
}

func (t *FollowUpSignalClassView) PropertyWake_agenda() (ClassPropertyView, error) {
	return t.inner.Property("wake_agenda")
}

func (t *TypeBuilder) FollowUpSignal() (*FollowUpSignalClassView, error) {
	bld, err := t.inner.Class("FollowUpSignal")
	if err != nil {
		return nil, err
	}
	return &FollowUpSignalClassView{inner: bld}, nil
}

func (t *FollowUpSignalClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TurnClassificationClassView struct {
	inner baml.ClassBuilder
}

func (t *TurnClassificationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TurnClassificationClassView) PropertyOutcome() (ClassPropertyView, error) {
	return t.inner.Property("outcome")
}

func (t *TurnClassificationClassView) PropertyInput_kind() (ClassPropertyView, error) {
	return t.inner.Property("input_kind")
}

func (t *TypeBuilder) TurnClassification() (*TurnClassificationClassView, error) {
	bld, err := t.inner.Class("TurnClassification")
	if err != nil {
		return nil, err
	}
	return &TurnClassificationClassView{inner: bld}, nil
}

func (t *TurnClassificationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type WakeAgendaItemClassView struct {
	inner baml.ClassBuilder
}

func (t *WakeAgendaItemClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *WakeAgendaItemClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *WakeAgendaItemClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *WakeAgendaItemClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *TypeBuilder) WakeAgendaItem() (*WakeAgendaItemClassView, error) {
	bld, err := t.inner.Class("WakeAgendaItem")
	if err != nil {
		return nil, err
	}
	return &WakeAgendaItemClassView{inner: bld}, nil
}

func (t *WakeAgendaItemClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
