// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/beam-cloud/airstore/pkg/worker/agentsignal/baml_client/stream_types"
	"github.com/beam-cloud/airstore/pkg/worker/agentsignal/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsError   bool
	Error     error
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
	return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
	return s.as_stream
}

// / Streaming version of ClassifyFollowUp
func (*stream) ClassifyFollowUp(ctx context.Context, message string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.FollowUpSignal, types.FollowUpSignal], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"message": message},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ClassifyFollowUp: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ClassifyFollowUp", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.FollowUpSignal, types.FollowUpSignal])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.FollowUpSignal, types.FollowUpSignal]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.FollowUpSignal)
				channel <- StreamValue[stream_types.FollowUpSignal, types.FollowUpSignal]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.FollowUpSignal)
				channel <- StreamValue[stream_types.FollowUpSignal, types.FollowUpSignal]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of ClassifyTurn
func (*stream) ClassifyTurn(ctx context.Context, message string, opts ...CallOptionFunc) (<-chan StreamValue[types.TurnOutcome, types.TurnOutcome], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"message": message},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ClassifyTurn: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ClassifyTurn", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[types.TurnOutcome, types.TurnOutcome])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[types.TurnOutcome, types.TurnOutcome]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.TurnOutcome)
				channel <- StreamValue[types.TurnOutcome, types.TurnOutcome]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(types.TurnOutcome)
				channel <- StreamValue[types.TurnOutcome, types.TurnOutcome]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of ExtractOutputs
func (*stream) ExtractOutputs(ctx context.Context, tool_name string, tool_input string, tool_result string, opts ...CallOptionFunc) (<-chan StreamValue[[]stream_types.ExtractedOutput, []types.ExtractedOutput], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"tool_name": tool_name, "tool_input": tool_input, "tool_result": tool_result},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExtractOutputs: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ExtractOutputs", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[[]stream_types.ExtractedOutput, []types.ExtractedOutput])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[[]stream_types.ExtractedOutput, []types.ExtractedOutput]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).([]types.ExtractedOutput)
				channel <- StreamValue[[]stream_types.ExtractedOutput, []types.ExtractedOutput]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).([]stream_types.ExtractedOutput)
				channel <- StreamValue[[]stream_types.ExtractedOutput, []types.ExtractedOutput]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}
