// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/beam-cloud/airstore/pkg/worker/agentsignal/baml_client/stream_types"
	"github.com/beam-cloud/airstore/pkg/worker/agentsignal/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.ApprovalSummary":           reflect.TypeOf(types.ApprovalSummary{}),
	"STREAM_TYPES.ApprovalSummary":    reflect.TypeOf(stream_types.ApprovalSummary{}),
	"TYPES.DataField":                 reflect.TypeOf(types.DataField{}),
	"STREAM_TYPES.DataField":          reflect.TypeOf(stream_types.DataField{}),
	"TYPES.ExtractedOutput":           reflect.TypeOf(types.ExtractedOutput{}),
	"STREAM_TYPES.ExtractedOutput":    reflect.TypeOf(stream_types.ExtractedOutput{}),
	"TYPES.FanOutSignal":              reflect.TypeOf(types.FanOutSignal{}),
	"STREAM_TYPES.FanOutSignal":       reflect.TypeOf(stream_types.FanOutSignal{}),
	"TYPES.FollowUpSignal":            reflect.TypeOf(types.FollowUpSignal{}),
	"STREAM_TYPES.FollowUpSignal":     reflect.TypeOf(stream_types.FollowUpSignal{}),
	"TYPES.SourceWatchRequest":        reflect.TypeOf(types.SourceWatchRequest{}),
	"STREAM_TYPES.SourceWatchRequest": reflect.TypeOf(stream_types.SourceWatchRequest{}),
	"TYPES.SubtaskSpec":               reflect.TypeOf(types.SubtaskSpec{}),
	"STREAM_TYPES.SubtaskSpec":        reflect.TypeOf(stream_types.SubtaskSpec{}),
	"TYPES.TurnClassification":        reflect.TypeOf(types.TurnClassification{}),
	"STREAM_TYPES.TurnClassification": reflect.TypeOf(stream_types.TurnClassification{}),
	"TYPES.WakeAgendaItem":            reflect.TypeOf(types.WakeAgendaItem{}),
	"STREAM_TYPES.WakeAgendaItem":     reflect.TypeOf(stream_types.WakeAgendaItem{}),

	"TYPES.FanOutIntent":   reflect.TypeOf(types.FanOutIntent("")),
	"TYPES.FollowUpIntent": reflect.TypeOf(types.FollowUpIntent("")),
	"TYPES.InputKind":      reflect.TypeOf(types.InputKind("")),
	"TYPES.OutputKind":     reflect.TypeOf(types.OutputKind("")),
	"TYPES.TurnOutcome":    reflect.TypeOf(types.TurnOutcome("")),
}
