// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/beam-cloud/airstore/pkg/views/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

func MapOutputsToSchema(ctx context.Context, sheet_name string, table_title string, table_type string, row_strategy_mode string, row_strategy_description string, columns []types.ColumnSchema, outputs_json string, opts ...CallOptionFunc) (types.MappedResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"sheet_name": sheet_name, "table_title": table_title, "table_type": table_type, "row_strategy_mode": row_strategy_mode, "row_strategy_description": row_strategy_description, "columns": columns, "outputs_json": outputs_json},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "MapOutputsToSchema", encoded, callOpts.onTick)
		if err != nil {
			return types.MappedResult{}, err
		}

		if result.Error != nil {
			return types.MappedResult{}, result.Error
		}

		casted := (result.Data).(types.MappedResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "MapOutputsToSchema", encoded, callOpts.onTick)
		if err != nil {
			return types.MappedResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.MappedResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.MappedResult), nil
			}
		}

		return types.MappedResult{}, fmt.Errorf("No data returned from stream")
	}
}

func WriteView(ctx context.Context, user_message string, conversation_history string, current_view string, workspace_context string, component_registry string, opts ...CallOptionFunc) (types.ViewDraftResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_message": user_message, "conversation_history": conversation_history, "current_view": current_view, "workspace_context": workspace_context, "component_registry": component_registry},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "WriteView", encoded, callOpts.onTick)
		if err != nil {
			return types.ViewDraftResponse{}, err
		}

		if result.Error != nil {
			return types.ViewDraftResponse{}, result.Error
		}

		casted := (result.Data).(types.ViewDraftResponse)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "WriteView", encoded, callOpts.onTick)
		if err != nil {
			return types.ViewDraftResponse{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ViewDraftResponse{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ViewDraftResponse), nil
			}
		}

		return types.ViewDraftResponse{}, fmt.Errorf("No data returned from stream")
	}
}
