// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/beam-cloud/airstore/pkg/views/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type build_request struct{}

var Request = &build_request{}

// Build HTTP request for ClassifyDetailTemplate (returns baml.HTTPRequest)
func (*build_request) ClassifyDetailTemplate(table_title string, column_schema string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"table_title": table_title, "column_schema": column_schema, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ClassifyDetailTemplate: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "ClassifyDetailTemplate", encoded)
}

// Build HTTP request for MapImportColumns (returns baml.HTTPRequest)
func (*build_request) MapImportColumns(sheet_name string, existing_columns []types.ColumnSchema, headers []string, data_preview string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"sheet_name": sheet_name, "existing_columns": existing_columns, "headers": headers, "data_preview": data_preview, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: MapImportColumns: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "MapImportColumns", encoded)
}

// Build HTTP request for MapOutputsToSchema (returns baml.HTTPRequest)
func (*build_request) MapOutputsToSchema(sheet_name string, table_title string, table_type string, columns []types.ColumnSchema, outputs_payload string, existing_rows string, excluded_rows string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"sheet_name": sheet_name, "table_title": table_title, "table_type": table_type, "columns": columns, "outputs_payload": outputs_payload, "existing_rows": existing_rows, "excluded_rows": excluded_rows, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: MapOutputsToSchema: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "MapOutputsToSchema", encoded)
}

// Build HTTP request for MapViewToWidget (returns baml.HTTPRequest)
func (*build_request) MapViewToWidget(sheet_name string, widget_type string, widget_title string, widget_description string, widget_config string, table_columns string, table_data string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"sheet_name": sheet_name, "widget_type": widget_type, "widget_title": widget_title, "widget_description": widget_description, "widget_config": widget_config, "table_columns": table_columns, "table_data": table_data, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: MapViewToWidget: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "MapViewToWidget", encoded)
}

// Build HTTP request for WriteView (returns baml.HTTPRequest)
func (*build_request) WriteView(user_message string, conversation_history string, current_view string, workspace_context string, component_registry string, view_data string, active_tasks string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_message": user_message, "conversation_history": conversation_history, "current_view": current_view, "workspace_context": workspace_context, "component_registry": component_registry, "view_data": view_data, "active_tasks": active_tasks, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: WriteView: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "WriteView", encoded)
}
