// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/beam-cloud/airstore/pkg/views/baml_client/stream_types"
	"github.com/beam-cloud/airstore/pkg/views/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AffectedRowsResult":         reflect.TypeOf(types.AffectedRowsResult{}),
	"STREAM_TYPES.AffectedRowsResult":  reflect.TypeOf(stream_types.AffectedRowsResult{}),
	"TYPES.ColumnSchema":               reflect.TypeOf(types.ColumnSchema{}),
	"STREAM_TYPES.ColumnSchema":        reflect.TypeOf(stream_types.ColumnSchema{}),
	"TYPES.DataCitation":               reflect.TypeOf(types.DataCitation{}),
	"STREAM_TYPES.DataCitation":        reflect.TypeOf(stream_types.DataCitation{}),
	"TYPES.DetailLayout":               reflect.TypeOf(types.DetailLayout{}),
	"STREAM_TYPES.DetailLayout":        reflect.TypeOf(stream_types.DetailLayout{}),
	"TYPES.DetailSection":              reflect.TypeOf(types.DetailSection{}),
	"STREAM_TYPES.DetailSection":       reflect.TypeOf(stream_types.DetailSection{}),
	"TYPES.ImportColumnMatch":          reflect.TypeOf(types.ImportColumnMatch{}),
	"STREAM_TYPES.ImportColumnMatch":   reflect.TypeOf(stream_types.ImportColumnMatch{}),
	"TYPES.ImportMappingResult":        reflect.TypeOf(types.ImportMappingResult{}),
	"STREAM_TYPES.ImportMappingResult": reflect.TypeOf(stream_types.ImportMappingResult{}),
	"TYPES.ListItemResult":             reflect.TypeOf(types.ListItemResult{}),
	"STREAM_TYPES.ListItemResult":      reflect.TypeOf(stream_types.ListItemResult{}),
	"TYPES.ListResult":                 reflect.TypeOf(types.ListResult{}),
	"STREAM_TYPES.ListResult":          reflect.TypeOf(stream_types.ListResult{}),
	"TYPES.MapMarkerResult":            reflect.TypeOf(types.MapMarkerResult{}),
	"STREAM_TYPES.MapMarkerResult":     reflect.TypeOf(stream_types.MapMarkerResult{}),
	"TYPES.MapResult":                  reflect.TypeOf(types.MapResult{}),
	"STREAM_TYPES.MapResult":           reflect.TypeOf(stream_types.MapResult{}),
	"TYPES.MappedCell":                 reflect.TypeOf(types.MappedCell{}),
	"STREAM_TYPES.MappedCell":          reflect.TypeOf(stream_types.MappedCell{}),
	"TYPES.MappedResult":               reflect.TypeOf(types.MappedResult{}),
	"STREAM_TYPES.MappedResult":        reflect.TypeOf(stream_types.MappedResult{}),
	"TYPES.MappedRow":                  reflect.TypeOf(types.MappedRow{}),
	"STREAM_TYPES.MappedRow":           reflect.TypeOf(stream_types.MappedRow{}),
	"TYPES.MetricResult":               reflect.TypeOf(types.MetricResult{}),
	"STREAM_TYPES.MetricResult":        reflect.TypeOf(stream_types.MetricResult{}),
	"TYPES.Operation":                  reflect.TypeOf(types.Operation{}),
	"STREAM_TYPES.Operation":           reflect.TypeOf(stream_types.Operation{}),
	"TYPES.PopulateRowResult":          reflect.TypeOf(types.PopulateRowResult{}),
	"STREAM_TYPES.PopulateRowResult":   reflect.TypeOf(stream_types.PopulateRowResult{}),
	"TYPES.RowSearchPlan":              reflect.TypeOf(types.RowSearchPlan{}),
	"STREAM_TYPES.RowSearchPlan":       reflect.TypeOf(stream_types.RowSearchPlan{}),
	"TYPES.SearchCriterion":            reflect.TypeOf(types.SearchCriterion{}),
	"STREAM_TYPES.SearchCriterion":     reflect.TypeOf(stream_types.SearchCriterion{}),
	"TYPES.ViewCell":                   reflect.TypeOf(types.ViewCell{}),
	"STREAM_TYPES.ViewCell":            reflect.TypeOf(stream_types.ViewCell{}),
	"TYPES.ViewColumn":                 reflect.TypeOf(types.ViewColumn{}),
	"STREAM_TYPES.ViewColumn":          reflect.TypeOf(stream_types.ViewColumn{}),
	"TYPES.ViewDraftResponse":          reflect.TypeOf(types.ViewDraftResponse{}),
	"STREAM_TYPES.ViewDraftResponse":   reflect.TypeOf(stream_types.ViewDraftResponse{}),
	"TYPES.WidgetResult":               reflect.TypeOf(types.WidgetResult{}),
	"STREAM_TYPES.WidgetResult":        reflect.TypeOf(stream_types.WidgetResult{}),

	"TYPES.OperationType":   reflect.TypeOf(types.OperationType("")),
	"TYPES.SectionEmphasis": reflect.TypeOf(types.SectionEmphasis("")),
	"TYPES.SectionType":     reflect.TypeOf(types.SectionType("")),
	"TYPES.ViewUpdateType":  reflect.TypeOf(types.ViewUpdateType("")),
}
