// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type ColumnAction string

const (
	ColumnActionMatch  ColumnAction = "Match"
	ColumnActionCreate ColumnAction = "Create"
	ColumnActionSkip   ColumnAction = "Skip"
)

// Values returns all allowed values for the ColumnAction type.
func (ColumnAction) Values() []ColumnAction {
	return []ColumnAction{
		ColumnActionMatch,
		ColumnActionCreate,
		ColumnActionSkip,
	}
}

// IsValid checks whether the given ColumnAction value is valid.
func (e ColumnAction) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for ColumnAction.
func (e ColumnAction) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid ColumnAction: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for ColumnAction.
func (e *ColumnAction) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = ColumnAction(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid ColumnAction: %q", s)
	}
	return nil
}

func (e *ColumnAction) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "ColumnAction" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.ColumnAction, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = ColumnAction(value)
}

func (e ColumnAction) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("ColumnAction", string(e), false)
}

func (e ColumnAction) BamlTypeName() string {
	return "ColumnAction"
}

type OperationType string

const (
	OperationTypeCREATE_AGENT    OperationType = "CREATE_AGENT"
	OperationTypeUPDATE_AGENT    OperationType = "UPDATE_AGENT"
	OperationTypeCREATE_SKILL    OperationType = "CREATE_SKILL"
	OperationTypeINSTALL_SKILL   OperationType = "INSTALL_SKILL"
	OperationTypeASSIGN_SKILL    OperationType = "ASSIGN_SKILL"
	OperationTypeDISPATCH_TASK   OperationType = "DISPATCH_TASK"
	OperationTypeAPPROVE_TASK    OperationType = "APPROVE_TASK"
	OperationTypeREJECT_TASK     OperationType = "REJECT_TASK"
	OperationTypeCREATE_SCHEDULE OperationType = "CREATE_SCHEDULE"
	OperationTypeDELETE_SCHEDULE OperationType = "DELETE_SCHEDULE"
	OperationTypeIMPORT_DATA     OperationType = "IMPORT_DATA"
)

// Values returns all allowed values for the OperationType type.
func (OperationType) Values() []OperationType {
	return []OperationType{
		OperationTypeCREATE_AGENT,
		OperationTypeUPDATE_AGENT,
		OperationTypeCREATE_SKILL,
		OperationTypeINSTALL_SKILL,
		OperationTypeASSIGN_SKILL,
		OperationTypeDISPATCH_TASK,
		OperationTypeAPPROVE_TASK,
		OperationTypeREJECT_TASK,
		OperationTypeCREATE_SCHEDULE,
		OperationTypeDELETE_SCHEDULE,
		OperationTypeIMPORT_DATA,
	}
}

// IsValid checks whether the given OperationType value is valid.
func (e OperationType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for OperationType.
func (e OperationType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid OperationType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for OperationType.
func (e *OperationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = OperationType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid OperationType: %q", s)
	}
	return nil
}

func (e *OperationType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "OperationType" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.OperationType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = OperationType(value)
}

func (e OperationType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("OperationType", string(e), false)
}

func (e OperationType) BamlTypeName() string {
	return "OperationType"
}

type SectionEmphasis string

const (
	SectionEmphasisPRIMARY   SectionEmphasis = "PRIMARY"
	SectionEmphasisSECONDARY SectionEmphasis = "SECONDARY"
	SectionEmphasisCOLLAPSED SectionEmphasis = "COLLAPSED"
)

// Values returns all allowed values for the SectionEmphasis type.
func (SectionEmphasis) Values() []SectionEmphasis {
	return []SectionEmphasis{
		SectionEmphasisPRIMARY,
		SectionEmphasisSECONDARY,
		SectionEmphasisCOLLAPSED,
	}
}

// IsValid checks whether the given SectionEmphasis value is valid.
func (e SectionEmphasis) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for SectionEmphasis.
func (e SectionEmphasis) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid SectionEmphasis: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for SectionEmphasis.
func (e *SectionEmphasis) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = SectionEmphasis(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid SectionEmphasis: %q", s)
	}
	return nil
}

func (e *SectionEmphasis) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "SectionEmphasis" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.SectionEmphasis, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = SectionEmphasis(value)
}

func (e SectionEmphasis) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("SectionEmphasis", string(e), false)
}

func (e SectionEmphasis) BamlTypeName() string {
	return "SectionEmphasis"
}

type SectionType string

const (
	SectionTypeEMAIL_THREAD   SectionType = "EMAIL_THREAD"
	SectionTypeAPPROVAL       SectionType = "APPROVAL"
	SectionTypeINPUT_FORM     SectionType = "INPUT_FORM"
	SectionTypeTASK_PROGRESS  SectionType = "TASK_PROGRESS"
	SectionTypeOUTPUT_GALLERY SectionType = "OUTPUT_GALLERY"
	SectionTypeDATA_SUMMARY   SectionType = "DATA_SUMMARY"
	SectionTypeSUBTASKS       SectionType = "SUBTASKS"
)

// Values returns all allowed values for the SectionType type.
func (SectionType) Values() []SectionType {
	return []SectionType{
		SectionTypeEMAIL_THREAD,
		SectionTypeAPPROVAL,
		SectionTypeINPUT_FORM,
		SectionTypeTASK_PROGRESS,
		SectionTypeOUTPUT_GALLERY,
		SectionTypeDATA_SUMMARY,
		SectionTypeSUBTASKS,
	}
}

// IsValid checks whether the given SectionType value is valid.
func (e SectionType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for SectionType.
func (e SectionType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid SectionType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for SectionType.
func (e *SectionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = SectionType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid SectionType: %q", s)
	}
	return nil
}

func (e *SectionType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "SectionType" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.SectionType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = SectionType(value)
}

func (e SectionType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("SectionType", string(e), false)
}

func (e SectionType) BamlTypeName() string {
	return "SectionType"
}

type ViewUpdateType string

const (
	ViewUpdateTypeCONVERSATION     ViewUpdateType = "CONVERSATION"
	ViewUpdateTypeVIEW_CREATE      ViewUpdateType = "VIEW_CREATE"
	ViewUpdateTypeLAYOUT_CHANGE    ViewUpdateType = "LAYOUT_CHANGE"
	ViewUpdateTypeCOMPONENT_ADD    ViewUpdateType = "COMPONENT_ADD"
	ViewUpdateTypeCOMPONENT_EDIT   ViewUpdateType = "COMPONENT_EDIT"
	ViewUpdateTypeCOMPONENT_REMOVE ViewUpdateType = "COMPONENT_REMOVE"
	ViewUpdateTypeDATA_REBIND      ViewUpdateType = "DATA_REBIND"
	ViewUpdateTypeINFRASTRUCTURE   ViewUpdateType = "INFRASTRUCTURE"
)

// Values returns all allowed values for the ViewUpdateType type.
func (ViewUpdateType) Values() []ViewUpdateType {
	return []ViewUpdateType{
		ViewUpdateTypeCONVERSATION,
		ViewUpdateTypeVIEW_CREATE,
		ViewUpdateTypeLAYOUT_CHANGE,
		ViewUpdateTypeCOMPONENT_ADD,
		ViewUpdateTypeCOMPONENT_EDIT,
		ViewUpdateTypeCOMPONENT_REMOVE,
		ViewUpdateTypeDATA_REBIND,
		ViewUpdateTypeINFRASTRUCTURE,
	}
}

// IsValid checks whether the given ViewUpdateType value is valid.
func (e ViewUpdateType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for ViewUpdateType.
func (e ViewUpdateType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid ViewUpdateType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for ViewUpdateType.
func (e *ViewUpdateType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = ViewUpdateType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid ViewUpdateType: %q", s)
	}
	return nil
}

func (e *ViewUpdateType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "ViewUpdateType" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.ViewUpdateType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = ViewUpdateType(value)
}

func (e ViewUpdateType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("ViewUpdateType", string(e), false)
}

func (e ViewUpdateType) BamlTypeName() string {
	return "ViewUpdateType"
}
