// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type OperationType string

const (
	OperationTypeCREATE_AGENT  OperationType = "CREATE_AGENT"
	OperationTypeUPDATE_AGENT  OperationType = "UPDATE_AGENT"
	OperationTypeCREATE_SKILL  OperationType = "CREATE_SKILL"
	OperationTypeINSTALL_SKILL OperationType = "INSTALL_SKILL"
	OperationTypeASSIGN_SKILL  OperationType = "ASSIGN_SKILL"
)

// Values returns all allowed values for the OperationType type.
func (OperationType) Values() []OperationType {
	return []OperationType{
		OperationTypeCREATE_AGENT,
		OperationTypeUPDATE_AGENT,
		OperationTypeCREATE_SKILL,
		OperationTypeINSTALL_SKILL,
		OperationTypeASSIGN_SKILL,
	}
}

// IsValid checks whether the given OperationType value is valid.
func (e OperationType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for OperationType.
func (e OperationType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid OperationType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for OperationType.
func (e *OperationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = OperationType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid OperationType: %q", s)
	}
	return nil
}

func (e *OperationType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "OperationType" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.OperationType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = OperationType(value)
}

func (e OperationType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("OperationType", string(e), false)
}

func (e OperationType) BamlTypeName() string {
	return "OperationType"
}

type ViewUpdateType string

const (
	ViewUpdateTypeCONVERSATION     ViewUpdateType = "CONVERSATION"
	ViewUpdateTypeVIEW_CREATE      ViewUpdateType = "VIEW_CREATE"
	ViewUpdateTypeLAYOUT_CHANGE    ViewUpdateType = "LAYOUT_CHANGE"
	ViewUpdateTypeCOMPONENT_ADD    ViewUpdateType = "COMPONENT_ADD"
	ViewUpdateTypeCOMPONENT_EDIT   ViewUpdateType = "COMPONENT_EDIT"
	ViewUpdateTypeCOMPONENT_REMOVE ViewUpdateType = "COMPONENT_REMOVE"
	ViewUpdateTypeDATA_REBIND      ViewUpdateType = "DATA_REBIND"
	ViewUpdateTypeINFRASTRUCTURE   ViewUpdateType = "INFRASTRUCTURE"
)

// Values returns all allowed values for the ViewUpdateType type.
func (ViewUpdateType) Values() []ViewUpdateType {
	return []ViewUpdateType{
		ViewUpdateTypeCONVERSATION,
		ViewUpdateTypeVIEW_CREATE,
		ViewUpdateTypeLAYOUT_CHANGE,
		ViewUpdateTypeCOMPONENT_ADD,
		ViewUpdateTypeCOMPONENT_EDIT,
		ViewUpdateTypeCOMPONENT_REMOVE,
		ViewUpdateTypeDATA_REBIND,
		ViewUpdateTypeINFRASTRUCTURE,
	}
}

// IsValid checks whether the given ViewUpdateType value is valid.
func (e ViewUpdateType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for ViewUpdateType.
func (e ViewUpdateType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid ViewUpdateType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for ViewUpdateType.
func (e *ViewUpdateType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = ViewUpdateType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid ViewUpdateType: %q", s)
	}
	return nil
}

func (e *ViewUpdateType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "ViewUpdateType" || name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.ViewUpdateType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = ViewUpdateType(value)
}

func (e ViewUpdateType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("ViewUpdateType", string(e), false)
}

func (e ViewUpdateType) BamlTypeName() string {
	return "ViewUpdateType"
}
