// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type GDriveQueryResult struct {
	Gdrive_query    string `json:"gdrive_query"`
	Limit           int64  `json:"limit"`
	Filename_format string `json:"filename_format"`
}

func (c *GDriveQueryResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GDriveQueryResult" {
		panic(fmt.Sprintf("expected GDriveQueryResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "gdrive_query":
			c.Gdrive_query = baml.Decode(valueHolder).Interface().(string)

		case "limit":
			c.Limit = baml.Decode(valueHolder).Int()

		case "filename_format":
			c.Filename_format = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GDriveQueryResult", key))

		}
	}

}

func (c GDriveQueryResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["gdrive_query"] = c.Gdrive_query

	fields["limit"] = c.Limit

	fields["filename_format"] = c.Filename_format

	return baml.EncodeClass("GDriveQueryResult", fields, nil)
}

func (c GDriveQueryResult) BamlTypeName() string {
	return "GDriveQueryResult"
}

type GmailQueryResult struct {
	Gmail_query     string `json:"gmail_query"`
	Limit           int64  `json:"limit"`
	Filename_format string `json:"filename_format"`
}

func (c *GmailQueryResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GmailQueryResult" {
		panic(fmt.Sprintf("expected GmailQueryResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "gmail_query":
			c.Gmail_query = baml.Decode(valueHolder).Interface().(string)

		case "limit":
			c.Limit = baml.Decode(valueHolder).Int()

		case "filename_format":
			c.Filename_format = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GmailQueryResult", key))

		}
	}

}

func (c GmailQueryResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["gmail_query"] = c.Gmail_query

	fields["limit"] = c.Limit

	fields["filename_format"] = c.Filename_format

	return baml.EncodeClass("GmailQueryResult", fields, nil)
}

func (c GmailQueryResult) BamlTypeName() string {
	return "GmailQueryResult"
}

type NotionQueryResult struct {
	Notion_query    string `json:"notion_query"`
	Limit           int64  `json:"limit"`
	Filename_format string `json:"filename_format"`
}

func (c *NotionQueryResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "NotionQueryResult" {
		panic(fmt.Sprintf("expected NotionQueryResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "notion_query":
			c.Notion_query = baml.Decode(valueHolder).Interface().(string)

		case "limit":
			c.Limit = baml.Decode(valueHolder).Int()

		case "filename_format":
			c.Filename_format = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class NotionQueryResult", key))

		}
	}

}

func (c NotionQueryResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["notion_query"] = c.Notion_query

	fields["limit"] = c.Limit

	fields["filename_format"] = c.Filename_format

	return baml.EncodeClass("NotionQueryResult", fields, nil)
}

func (c NotionQueryResult) BamlTypeName() string {
	return "NotionQueryResult"
}
