// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/beam-cloud/airstore/pkg/channels/inbound/baml_client/stream_types"
	"github.com/beam-cloud/airstore/pkg/channels/inbound/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.ActiveTask":             reflect.TypeOf(types.ActiveTask{}),
	"STREAM_TYPES.ActiveTask":      reflect.TypeOf(stream_types.ActiveTask{}),
	"TYPES.AvailableAgent":         reflect.TypeOf(types.AvailableAgent{}),
	"STREAM_TYPES.AvailableAgent":  reflect.TypeOf(stream_types.AvailableAgent{}),
	"TYPES.InboundResponse":        reflect.TypeOf(types.InboundResponse{}),
	"STREAM_TYPES.InboundResponse": reflect.TypeOf(stream_types.InboundResponse{}),
	"TYPES.InboundTask":            reflect.TypeOf(types.InboundTask{}),
	"STREAM_TYPES.InboundTask":     reflect.TypeOf(stream_types.InboundTask{}),
	"TYPES.InferredOutput":         reflect.TypeOf(types.InferredOutput{}),
	"STREAM_TYPES.InferredOutput":  reflect.TypeOf(stream_types.InferredOutput{}),
	"TYPES.TableColumn":            reflect.TypeOf(types.TableColumn{}),
	"STREAM_TYPES.TableColumn":     reflect.TypeOf(stream_types.TableColumn{}),

	"TYPES.InboundTaskType": reflect.TypeOf(types.InboundTaskType("")),

	"TYPES.string_badge__string_currency__string_link":                       reflect.TypeOf(types.Union3KbadgeOrKcurrencyOrKlink{}),
	"TYPES.string_boolean__string_date__string_number__string_string":        reflect.TypeOf(types.Union4KbooleanOrKdateOrKnumberOrKstring{}),
	"TYPES.string_file__string_json__string_link__string_table__string_text": reflect.TypeOf(types.Union5KfileOrKjsonOrKlinkOrKtableOrKtext{}),
}
