// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type OperationTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *OperationTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *OperationTypeEnumView) ValueCREATE_AGENT() (EnumValueView, error) {
	return t.inner.Value("CREATE_AGENT")
}

func (t *OperationTypeEnumView) ValueUPDATE_AGENT() (EnumValueView, error) {
	return t.inner.Value("UPDATE_AGENT")
}

func (t *OperationTypeEnumView) ValueCREATE_SKILL() (EnumValueView, error) {
	return t.inner.Value("CREATE_SKILL")
}

func (t *OperationTypeEnumView) ValueINSTALL_SKILL() (EnumValueView, error) {
	return t.inner.Value("INSTALL_SKILL")
}

func (t *OperationTypeEnumView) ValueASSIGN_SKILL() (EnumValueView, error) {
	return t.inner.Value("ASSIGN_SKILL")
}

func (t *OperationTypeEnumView) ValueDISPATCH_TASK() (EnumValueView, error) {
	return t.inner.Value("DISPATCH_TASK")
}

func (t *OperationTypeEnumView) ValueAPPROVE_TASK() (EnumValueView, error) {
	return t.inner.Value("APPROVE_TASK")
}

func (t *OperationTypeEnumView) ValueREJECT_TASK() (EnumValueView, error) {
	return t.inner.Value("REJECT_TASK")
}

func (t *OperationTypeEnumView) ValueCREATE_SCHEDULE() (EnumValueView, error) {
	return t.inner.Value("CREATE_SCHEDULE")
}

func (t *OperationTypeEnumView) ValueDELETE_SCHEDULE() (EnumValueView, error) {
	return t.inner.Value("DELETE_SCHEDULE")
}

func (t *TypeBuilder) OperationType() (*OperationTypeEnumView, error) {
	bld, err := t.inner.Enum("OperationType")
	if err != nil {
		return nil, err
	}
	return &OperationTypeEnumView{inner: bld}, nil
}

func (t *OperationTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SectionEmphasisEnumView struct {
	inner baml.EnumBuilder
}

func (t *SectionEmphasisEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SectionEmphasisEnumView) ValuePRIMARY() (EnumValueView, error) {
	return t.inner.Value("PRIMARY")
}

func (t *SectionEmphasisEnumView) ValueSECONDARY() (EnumValueView, error) {
	return t.inner.Value("SECONDARY")
}

func (t *SectionEmphasisEnumView) ValueCOLLAPSED() (EnumValueView, error) {
	return t.inner.Value("COLLAPSED")
}

func (t *TypeBuilder) SectionEmphasis() (*SectionEmphasisEnumView, error) {
	bld, err := t.inner.Enum("SectionEmphasis")
	if err != nil {
		return nil, err
	}
	return &SectionEmphasisEnumView{inner: bld}, nil
}

func (t *SectionEmphasisEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SectionTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *SectionTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SectionTypeEnumView) ValueEMAIL_THREAD() (EnumValueView, error) {
	return t.inner.Value("EMAIL_THREAD")
}

func (t *SectionTypeEnumView) ValueAPPROVAL() (EnumValueView, error) {
	return t.inner.Value("APPROVAL")
}

func (t *SectionTypeEnumView) ValueINPUT_FORM() (EnumValueView, error) {
	return t.inner.Value("INPUT_FORM")
}

func (t *SectionTypeEnumView) ValueTASK_PROGRESS() (EnumValueView, error) {
	return t.inner.Value("TASK_PROGRESS")
}

func (t *SectionTypeEnumView) ValueOUTPUT_GALLERY() (EnumValueView, error) {
	return t.inner.Value("OUTPUT_GALLERY")
}

func (t *SectionTypeEnumView) ValueDATA_SUMMARY() (EnumValueView, error) {
	return t.inner.Value("DATA_SUMMARY")
}

func (t *SectionTypeEnumView) ValueSUBTASKS() (EnumValueView, error) {
	return t.inner.Value("SUBTASKS")
}

func (t *TypeBuilder) SectionType() (*SectionTypeEnumView, error) {
	bld, err := t.inner.Enum("SectionType")
	if err != nil {
		return nil, err
	}
	return &SectionTypeEnumView{inner: bld}, nil
}

func (t *SectionTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ViewUpdateTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ViewUpdateTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ViewUpdateTypeEnumView) ValueCONVERSATION() (EnumValueView, error) {
	return t.inner.Value("CONVERSATION")
}

func (t *ViewUpdateTypeEnumView) ValueVIEW_CREATE() (EnumValueView, error) {
	return t.inner.Value("VIEW_CREATE")
}

func (t *ViewUpdateTypeEnumView) ValueLAYOUT_CHANGE() (EnumValueView, error) {
	return t.inner.Value("LAYOUT_CHANGE")
}

func (t *ViewUpdateTypeEnumView) ValueCOMPONENT_ADD() (EnumValueView, error) {
	return t.inner.Value("COMPONENT_ADD")
}

func (t *ViewUpdateTypeEnumView) ValueCOMPONENT_EDIT() (EnumValueView, error) {
	return t.inner.Value("COMPONENT_EDIT")
}

func (t *ViewUpdateTypeEnumView) ValueCOMPONENT_REMOVE() (EnumValueView, error) {
	return t.inner.Value("COMPONENT_REMOVE")
}

func (t *ViewUpdateTypeEnumView) ValueDATA_REBIND() (EnumValueView, error) {
	return t.inner.Value("DATA_REBIND")
}

func (t *ViewUpdateTypeEnumView) ValueINFRASTRUCTURE() (EnumValueView, error) {
	return t.inner.Value("INFRASTRUCTURE")
}

func (t *TypeBuilder) ViewUpdateType() (*ViewUpdateTypeEnumView, error) {
	bld, err := t.inner.Enum("ViewUpdateType")
	if err != nil {
		return nil, err
	}
	return &ViewUpdateTypeEnumView{inner: bld}, nil
}

func (t *ViewUpdateTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
