// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type InboundTaskTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *InboundTaskTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *InboundTaskTypeEnumView) ValueCREATE_TASK() (EnumValueView, error) {
	return t.inner.Value("CREATE_TASK")
}

func (t *InboundTaskTypeEnumView) ValueUPDATE_TASK() (EnumValueView, error) {
	return t.inner.Value("UPDATE_TASK")
}

func (t *InboundTaskTypeEnumView) ValueESCALATE() (EnumValueView, error) {
	return t.inner.Value("ESCALATE")
}

func (t *TypeBuilder) InboundTaskType() (*InboundTaskTypeEnumView, error) {
	bld, err := t.inner.Enum("InboundTaskType")
	if err != nil {
		return nil, err
	}
	return &InboundTaskTypeEnumView{inner: bld}, nil
}

func (t *InboundTaskTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
