// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Union3KbadgeOrKcurrencyOrKlink struct {
	variant string

	variant_Klink *string

	variant_Kbadge *string

	variant_Kcurrency *string
}

func (u *Union3KbadgeOrKcurrencyOrKlink) Decode(holder *cffi.CFFIValueUnionVariant, typeMap baml.TypeMap) {
	valueHolder := holder.Value
	variantName := holder.ValueOptionName
	switch variantName {
	case "string_link":
		u.variant = "Klink"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Klink = &value
	case "string_badge":
		u.variant = "Kbadge"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kbadge = &value
	case "string_currency":
		u.variant = "Kcurrency"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kcurrency = &value

	default:
		panic(fmt.Sprintf("invalid union variant: %s", variantName))
	}
}

func (u Union3KbadgeOrKcurrencyOrKlink) Encode() (*cffi.HostValue, error) {
	switch u.variant {

	case "Klink":
		return baml.EncodeValue(*u.variant_Klink)

	case "Kbadge":
		return baml.EncodeValue(*u.variant_Kbadge)

	case "Kcurrency":
		return baml.EncodeValue(*u.variant_Kcurrency)

	case "":
		return nil, fmt.Errorf("invalid union variant: [unset]")
	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u Union3KbadgeOrKcurrencyOrKlink) BamlTypeName() string {
	return "Union3KbadgeOrKcurrencyOrKlink"
}

func (u Union3KbadgeOrKcurrencyOrKlink) MarshalJSON() ([]byte, error) {
	switch u.variant {

	case "Klink":
		return json.Marshal(u.variant_Klink)

	case "Kbadge":
		return json.Marshal(u.variant_Kbadge)

	case "Kcurrency":
		return json.Marshal(u.variant_Kcurrency)

	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u *Union3KbadgeOrKcurrencyOrKlink) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &u.variant_Klink)
	if err == nil {
		u.variant = "Klink"
		return nil
	} else {
		u.variant_Klink = nil
	}

	err = json.Unmarshal(data, &u.variant_Kbadge)
	if err == nil {
		u.variant = "Kbadge"
		return nil
	} else {
		u.variant_Kbadge = nil
	}

	err = json.Unmarshal(data, &u.variant_Kcurrency)
	if err == nil {
		u.variant = "Kcurrency"
		return nil
	} else {
		u.variant_Kcurrency = nil
	}

	return fmt.Errorf("invalid union variant: %s", string(data))
}

func Union3KbadgeOrKcurrencyOrKlink__NewKlink() Union3KbadgeOrKcurrencyOrKlink {

	var v string = "link"

	return Union3KbadgeOrKcurrencyOrKlink{
		variant:       "Klink",
		variant_Klink: &v,
	}
}

func (u *Union3KbadgeOrKcurrencyOrKlink) SetKlink() {

	var v string = "link"

	u.variant = "Klink"
	u.variant_Klink = &v

	u.variant_Kbadge = nil

	u.variant_Kcurrency = nil

}

func (u *Union3KbadgeOrKcurrencyOrKlink) IsKlink() bool {
	return u.variant == "Klink"
}

func (u *Union3KbadgeOrKcurrencyOrKlink) AsKlink() *string {
	if u.variant != "Klink" {
		return nil
	}
	return u.variant_Klink
}

func Union3KbadgeOrKcurrencyOrKlink__NewKbadge() Union3KbadgeOrKcurrencyOrKlink {

	var v string = "badge"

	return Union3KbadgeOrKcurrencyOrKlink{
		variant:        "Kbadge",
		variant_Kbadge: &v,
	}
}

func (u *Union3KbadgeOrKcurrencyOrKlink) SetKbadge() {

	var v string = "badge"

	u.variant = "Kbadge"
	u.variant_Kbadge = &v

	u.variant_Klink = nil

	u.variant_Kcurrency = nil

}

func (u *Union3KbadgeOrKcurrencyOrKlink) IsKbadge() bool {
	return u.variant == "Kbadge"
}

func (u *Union3KbadgeOrKcurrencyOrKlink) AsKbadge() *string {
	if u.variant != "Kbadge" {
		return nil
	}
	return u.variant_Kbadge
}

func Union3KbadgeOrKcurrencyOrKlink__NewKcurrency() Union3KbadgeOrKcurrencyOrKlink {

	var v string = "currency"

	return Union3KbadgeOrKcurrencyOrKlink{
		variant:           "Kcurrency",
		variant_Kcurrency: &v,
	}
}

func (u *Union3KbadgeOrKcurrencyOrKlink) SetKcurrency() {

	var v string = "currency"

	u.variant = "Kcurrency"
	u.variant_Kcurrency = &v

	u.variant_Klink = nil

	u.variant_Kbadge = nil

}

func (u *Union3KbadgeOrKcurrencyOrKlink) IsKcurrency() bool {
	return u.variant == "Kcurrency"
}

func (u *Union3KbadgeOrKcurrencyOrKlink) AsKcurrency() *string {
	if u.variant != "Kcurrency" {
		return nil
	}
	return u.variant_Kcurrency
}

type Union4KbooleanOrKdateOrKnumberOrKstring struct {
	variant string

	variant_Kstring *string

	variant_Knumber *string

	variant_Kboolean *string

	variant_Kdate *string
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) Decode(holder *cffi.CFFIValueUnionVariant, typeMap baml.TypeMap) {
	valueHolder := holder.Value
	variantName := holder.ValueOptionName
	switch variantName {
	case "string_string":
		u.variant = "Kstring"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kstring = &value
	case "string_number":
		u.variant = "Knumber"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Knumber = &value
	case "string_boolean":
		u.variant = "Kboolean"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kboolean = &value
	case "string_date":
		u.variant = "Kdate"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kdate = &value

	default:
		panic(fmt.Sprintf("invalid union variant: %s", variantName))
	}
}

func (u Union4KbooleanOrKdateOrKnumberOrKstring) Encode() (*cffi.HostValue, error) {
	switch u.variant {

	case "Kstring":
		return baml.EncodeValue(*u.variant_Kstring)

	case "Knumber":
		return baml.EncodeValue(*u.variant_Knumber)

	case "Kboolean":
		return baml.EncodeValue(*u.variant_Kboolean)

	case "Kdate":
		return baml.EncodeValue(*u.variant_Kdate)

	case "":
		return nil, fmt.Errorf("invalid union variant: [unset]")
	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u Union4KbooleanOrKdateOrKnumberOrKstring) BamlTypeName() string {
	return "Union4KbooleanOrKdateOrKnumberOrKstring"
}

func (u Union4KbooleanOrKdateOrKnumberOrKstring) MarshalJSON() ([]byte, error) {
	switch u.variant {

	case "Kstring":
		return json.Marshal(u.variant_Kstring)

	case "Knumber":
		return json.Marshal(u.variant_Knumber)

	case "Kboolean":
		return json.Marshal(u.variant_Kboolean)

	case "Kdate":
		return json.Marshal(u.variant_Kdate)

	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &u.variant_Kstring)
	if err == nil {
		u.variant = "Kstring"
		return nil
	} else {
		u.variant_Kstring = nil
	}

	err = json.Unmarshal(data, &u.variant_Knumber)
	if err == nil {
		u.variant = "Knumber"
		return nil
	} else {
		u.variant_Knumber = nil
	}

	err = json.Unmarshal(data, &u.variant_Kboolean)
	if err == nil {
		u.variant = "Kboolean"
		return nil
	} else {
		u.variant_Kboolean = nil
	}

	err = json.Unmarshal(data, &u.variant_Kdate)
	if err == nil {
		u.variant = "Kdate"
		return nil
	} else {
		u.variant_Kdate = nil
	}

	return fmt.Errorf("invalid union variant: %s", string(data))
}

func Union4KbooleanOrKdateOrKnumberOrKstring__NewKstring() Union4KbooleanOrKdateOrKnumberOrKstring {

	var v string = "string"

	return Union4KbooleanOrKdateOrKnumberOrKstring{
		variant:         "Kstring",
		variant_Kstring: &v,
	}
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) SetKstring() {

	var v string = "string"

	u.variant = "Kstring"
	u.variant_Kstring = &v

	u.variant_Knumber = nil

	u.variant_Kboolean = nil

	u.variant_Kdate = nil

}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) IsKstring() bool {
	return u.variant == "Kstring"
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) AsKstring() *string {
	if u.variant != "Kstring" {
		return nil
	}
	return u.variant_Kstring
}

func Union4KbooleanOrKdateOrKnumberOrKstring__NewKnumber() Union4KbooleanOrKdateOrKnumberOrKstring {

	var v string = "number"

	return Union4KbooleanOrKdateOrKnumberOrKstring{
		variant:         "Knumber",
		variant_Knumber: &v,
	}
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) SetKnumber() {

	var v string = "number"

	u.variant = "Knumber"
	u.variant_Knumber = &v

	u.variant_Kstring = nil

	u.variant_Kboolean = nil

	u.variant_Kdate = nil

}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) IsKnumber() bool {
	return u.variant == "Knumber"
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) AsKnumber() *string {
	if u.variant != "Knumber" {
		return nil
	}
	return u.variant_Knumber
}

func Union4KbooleanOrKdateOrKnumberOrKstring__NewKboolean() Union4KbooleanOrKdateOrKnumberOrKstring {

	var v string = "boolean"

	return Union4KbooleanOrKdateOrKnumberOrKstring{
		variant:          "Kboolean",
		variant_Kboolean: &v,
	}
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) SetKboolean() {

	var v string = "boolean"

	u.variant = "Kboolean"
	u.variant_Kboolean = &v

	u.variant_Kstring = nil

	u.variant_Knumber = nil

	u.variant_Kdate = nil

}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) IsKboolean() bool {
	return u.variant == "Kboolean"
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) AsKboolean() *string {
	if u.variant != "Kboolean" {
		return nil
	}
	return u.variant_Kboolean
}

func Union4KbooleanOrKdateOrKnumberOrKstring__NewKdate() Union4KbooleanOrKdateOrKnumberOrKstring {

	var v string = "date"

	return Union4KbooleanOrKdateOrKnumberOrKstring{
		variant:       "Kdate",
		variant_Kdate: &v,
	}
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) SetKdate() {

	var v string = "date"

	u.variant = "Kdate"
	u.variant_Kdate = &v

	u.variant_Kstring = nil

	u.variant_Knumber = nil

	u.variant_Kboolean = nil

}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) IsKdate() bool {
	return u.variant == "Kdate"
}

func (u *Union4KbooleanOrKdateOrKnumberOrKstring) AsKdate() *string {
	if u.variant != "Kdate" {
		return nil
	}
	return u.variant_Kdate
}

type Union5KfileOrKjsonOrKlinkOrKtableOrKtext struct {
	variant string

	variant_Ktable *string

	variant_Ktext *string

	variant_Kfile *string

	variant_Klink *string

	variant_Kjson *string
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) Decode(holder *cffi.CFFIValueUnionVariant, typeMap baml.TypeMap) {
	valueHolder := holder.Value
	variantName := holder.ValueOptionName
	switch variantName {
	case "string_table":
		u.variant = "Ktable"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Ktable = &value
	case "string_text":
		u.variant = "Ktext"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Ktext = &value
	case "string_file":
		u.variant = "Kfile"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kfile = &value
	case "string_link":
		u.variant = "Klink"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Klink = &value
	case "string_json":
		u.variant = "Kjson"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kjson = &value

	default:
		panic(fmt.Sprintf("invalid union variant: %s", variantName))
	}
}

func (u Union5KfileOrKjsonOrKlinkOrKtableOrKtext) Encode() (*cffi.HostValue, error) {
	switch u.variant {

	case "Ktable":
		return baml.EncodeValue(*u.variant_Ktable)

	case "Ktext":
		return baml.EncodeValue(*u.variant_Ktext)

	case "Kfile":
		return baml.EncodeValue(*u.variant_Kfile)

	case "Klink":
		return baml.EncodeValue(*u.variant_Klink)

	case "Kjson":
		return baml.EncodeValue(*u.variant_Kjson)

	case "":
		return nil, fmt.Errorf("invalid union variant: [unset]")
	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u Union5KfileOrKjsonOrKlinkOrKtableOrKtext) BamlTypeName() string {
	return "Union5KfileOrKjsonOrKlinkOrKtableOrKtext"
}

func (u Union5KfileOrKjsonOrKlinkOrKtableOrKtext) MarshalJSON() ([]byte, error) {
	switch u.variant {

	case "Ktable":
		return json.Marshal(u.variant_Ktable)

	case "Ktext":
		return json.Marshal(u.variant_Ktext)

	case "Kfile":
		return json.Marshal(u.variant_Kfile)

	case "Klink":
		return json.Marshal(u.variant_Klink)

	case "Kjson":
		return json.Marshal(u.variant_Kjson)

	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &u.variant_Ktable)
	if err == nil {
		u.variant = "Ktable"
		return nil
	} else {
		u.variant_Ktable = nil
	}

	err = json.Unmarshal(data, &u.variant_Ktext)
	if err == nil {
		u.variant = "Ktext"
		return nil
	} else {
		u.variant_Ktext = nil
	}

	err = json.Unmarshal(data, &u.variant_Kfile)
	if err == nil {
		u.variant = "Kfile"
		return nil
	} else {
		u.variant_Kfile = nil
	}

	err = json.Unmarshal(data, &u.variant_Klink)
	if err == nil {
		u.variant = "Klink"
		return nil
	} else {
		u.variant_Klink = nil
	}

	err = json.Unmarshal(data, &u.variant_Kjson)
	if err == nil {
		u.variant = "Kjson"
		return nil
	} else {
		u.variant_Kjson = nil
	}

	return fmt.Errorf("invalid union variant: %s", string(data))
}

func Union5KfileOrKjsonOrKlinkOrKtableOrKtext__NewKtable() Union5KfileOrKjsonOrKlinkOrKtableOrKtext {

	var v string = "table"

	return Union5KfileOrKjsonOrKlinkOrKtableOrKtext{
		variant:        "Ktable",
		variant_Ktable: &v,
	}
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) SetKtable() {

	var v string = "table"

	u.variant = "Ktable"
	u.variant_Ktable = &v

	u.variant_Ktext = nil

	u.variant_Kfile = nil

	u.variant_Klink = nil

	u.variant_Kjson = nil

}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) IsKtable() bool {
	return u.variant == "Ktable"
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) AsKtable() *string {
	if u.variant != "Ktable" {
		return nil
	}
	return u.variant_Ktable
}

func Union5KfileOrKjsonOrKlinkOrKtableOrKtext__NewKtext() Union5KfileOrKjsonOrKlinkOrKtableOrKtext {

	var v string = "text"

	return Union5KfileOrKjsonOrKlinkOrKtableOrKtext{
		variant:       "Ktext",
		variant_Ktext: &v,
	}
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) SetKtext() {

	var v string = "text"

	u.variant = "Ktext"
	u.variant_Ktext = &v

	u.variant_Ktable = nil

	u.variant_Kfile = nil

	u.variant_Klink = nil

	u.variant_Kjson = nil

}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) IsKtext() bool {
	return u.variant == "Ktext"
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) AsKtext() *string {
	if u.variant != "Ktext" {
		return nil
	}
	return u.variant_Ktext
}

func Union5KfileOrKjsonOrKlinkOrKtableOrKtext__NewKfile() Union5KfileOrKjsonOrKlinkOrKtableOrKtext {

	var v string = "file"

	return Union5KfileOrKjsonOrKlinkOrKtableOrKtext{
		variant:       "Kfile",
		variant_Kfile: &v,
	}
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) SetKfile() {

	var v string = "file"

	u.variant = "Kfile"
	u.variant_Kfile = &v

	u.variant_Ktable = nil

	u.variant_Ktext = nil

	u.variant_Klink = nil

	u.variant_Kjson = nil

}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) IsKfile() bool {
	return u.variant == "Kfile"
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) AsKfile() *string {
	if u.variant != "Kfile" {
		return nil
	}
	return u.variant_Kfile
}

func Union5KfileOrKjsonOrKlinkOrKtableOrKtext__NewKlink() Union5KfileOrKjsonOrKlinkOrKtableOrKtext {

	var v string = "link"

	return Union5KfileOrKjsonOrKlinkOrKtableOrKtext{
		variant:       "Klink",
		variant_Klink: &v,
	}
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) SetKlink() {

	var v string = "link"

	u.variant = "Klink"
	u.variant_Klink = &v

	u.variant_Ktable = nil

	u.variant_Ktext = nil

	u.variant_Kfile = nil

	u.variant_Kjson = nil

}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) IsKlink() bool {
	return u.variant == "Klink"
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) AsKlink() *string {
	if u.variant != "Klink" {
		return nil
	}
	return u.variant_Klink
}

func Union5KfileOrKjsonOrKlinkOrKtableOrKtext__NewKjson() Union5KfileOrKjsonOrKlinkOrKtableOrKtext {

	var v string = "json"

	return Union5KfileOrKjsonOrKlinkOrKtableOrKtext{
		variant:       "Kjson",
		variant_Kjson: &v,
	}
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) SetKjson() {

	var v string = "json"

	u.variant = "Kjson"
	u.variant_Kjson = &v

	u.variant_Ktable = nil

	u.variant_Ktext = nil

	u.variant_Kfile = nil

	u.variant_Klink = nil

}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) IsKjson() bool {
	return u.variant == "Kjson"
}

func (u *Union5KfileOrKjsonOrKlinkOrKtableOrKtext) AsKjson() *string {
	if u.variant != "Kjson" {
		return nil
	}
	return u.variant_Kjson
}
